"""
Django settings for SGHSENA project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-30lwvnr481$88qwt=1u1vx&xv%61r-9h#z_0sh!0bi1l=276nl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Models',
    'Templates',
    'Inicio',
    'Login',
    'Dashboard',
    'consultas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SGHSENA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SGHSENA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sghsena',  # <- string con el nombre de la base de datos
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'Models.Usuario'
AUTHENTICATION_BACKENDS = [
    'Models.backends.DocumentoOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL =  '/static/'
STATICFILES_DIRS = [BASE_DIR/'Templates'/'static']

#STATICFILES_DIRS = [BASE_DIR / 'Templates' / 'static']
#STATIC_ROOT = BASE_DIR / 'staticfiles'
# para que sirven esas lineas que agregue?
# sirve para que django sepa donde buscar los archivos estaticos como css, js, imagenes, etc., que linea exactamente? la 119? esa linea le dice a django que los archivos estaticos estan en la carpeta 'static' dentro de la carpeta 'Templates' en el directorio base del proyecto. , entonces si está bien escrito y es necesario para que django funcione correctamente con archivos estaticos.
# la 121? esa linea le dice a django que cuando se ejecute el comando collectstatic, todos los archivos estaticos se recopilaran en la carpeta 'staticfiles' en el directorio base del proyecto. esto es util para la implementacion en produccion, donde un servidor web puede servir estos archivos de manera eficiente.
# y la 122? , la que dice STATIC_ROOT = BASE_DIR / 'staticfiles' , esa linea define la ubicacion donde se recopilaran todos los archivos estaticos cuando se ejecute el comando collectstatic. es importante para la implementacion en produccion, ya que permite que un servidor web sirva estos archivos de manera eficiente.
# Y STATICFILES_DIRS? esa linea le dice a django que ademas de buscar archivos estaticos en las carpetas 'static' de cada aplicacion instalada, tambien debe buscar en la carpeta 'static' dentro de la carpeta 'Templates' en el directorio base del proyecto. esto es util si tienes archivos estaticos que no estan asociados a una aplicacion especifica.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
