# Generated by Django 5.2.7 on 2025-11-12 04:10

import Models.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id_ambiente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ambientes',
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(max_length=150)),
                ('programa_relacionado', models.CharField(max_length=100)),
                ('horas', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('nombres', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('es_lider', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'instructores',
            },
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('dias_jornada', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'jornadas',
            },
        ),
        migrations.CreateModel(
            name='NivelesFormacion',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'niveles_formacion',
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('modalidad', models.CharField(max_length=50)),
                ('id_ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.ambientes')),
                ('id_instructor_lider', models.ForeignKey(db_column='id_instructor_lider', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.instructores')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.jornadas')),
            ],
            options={
                'db_table': 'fichas',
            },
        ),
        migrations.CreateModel(
            name='CompetenciasFichas',
            fields=[
                ('id_comp_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('carril', models.CharField(max_length=50)),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.competencias')),
                ('id_ficha', models.ForeignKey(db_column='id_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.fichas')),
            ],
            options={
                'db_table': 'competencias_fichas',
            },
        ),
        migrations.CreateModel(
            name='HorasCumplidas',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horas_cumplidas', models.IntegerField(default=0)),
                ('id_ficha', models.ForeignKey(db_column='id_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.fichas')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.instructores')),
            ],
            options={
                'db_table': 'horas_cumplidas',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('horas_por_cumplir', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.instructores')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.ambientes')),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.competencias')),
                ('id_ficha', models.ForeignKey(db_column='id_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.fichas')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.instructores')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.jornadas')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.AddField(
            model_name='instructores',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.perfiles'),
        ),
        migrations.AddField(
            model_name='competencias',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.perfiles'),
        ),
        migrations.CreateModel(
            name='ProgramasFormacion',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=150)),
                ('id_nivel', models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.nivelesformacion')),
            ],
            options={
                'db_table': 'programas_formacion',
            },
        ),
        migrations.AddField(
            model_name='fichas',
            name='id_programa',
            field=models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.programasformacion'),
        ),
        migrations.CreateModel(
            name='ResultadosAprendizaje',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_resultado', models.CharField(max_length=200)),
                ('hora_resultado', models.IntegerField(default=0)),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.competencias')),
            ],
            options={
                'db_table': 'resultados_aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=150)),
                ('numero_documento', models.BigIntegerField(help_text='Exactamente 10 dígitos.', unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999), django.core.validators.RegexValidator(message='El número de documento debe tener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='N° de documento')),
                ('tipo', models.CharField(blank=True, choices=[('COORDINADOR', 'Coordinador'), ('INSTRUCTOR', 'Instructor')], max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', Models.managers.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='instructores',
            name='user',
            field=models.OneToOneField(error_messages={'blank': 'Debe seleccionar un usuario de tipo INSTRUCTOR.', 'null': 'Debe seleccionar un usuario de tipo INSTRUCTOR.', 'unique': 'Este usuario ya está asignado como Instructor.'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coordinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_documento', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coordinadores',
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('numero_documento__gte', 1000000000), ('numero_documento__lte', 9999999999)), name='usuario_numero_documento_10_digitos_rango'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('is_staff', True), _connector='OR'), name='usuario_superuser_implica_staff'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', False), ('tipo__isnull', True), ('tipo', 'COORDINADOR'), _connector='OR'), name='usuario_staff_tipo_coordinador'),
        ),
    ]
