# Generated by Django 5.2.7 on 2025-11-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornadas',
            name='dias_jornada',
        ),
        migrations.CreateModel(
            name='JornadaDia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='Models.jornadas')),
            ],
            options={
                'db_table': 'jornadas_dias',
            },
        ),
    ]
