# Generated by Django 5.2.7 on 2025-11-12 04:11

import Models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', Models.models.UsuarioManager()),
            ],
        ),
    ]
