# Generated by Django 5.2.7 on 2025-11-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_remove_jornadas_dias_jornada_jornadadia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='id_instructor',
        ),
        migrations.RemoveField(
            model_name='jornadadia',
            name='dia',
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadadia',
            name='Viernes',
            field=models.BooleanField(default=False),
        ),
    ]
