# Generated by Django 5.2.7 on 2025-11-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_remove_contratos_id_instructor_remove_jornadadia_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructores',
            name='contratos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructores', to='Models.contratos'),
        ),
    ]
