# Generated by Django 5.2.7 on 2025-11-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_instructores_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructores',
            name='contratos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructores', to='Models.contratos'),
        ),
    ]
