# Generated by Django 5.2.7 on 2025-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_alter_instructores_contratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructores',
            name='contratos',
        ),
    ]
